language: smalltalk
sudo: false
smalltalk:
    - Pharo-5.0
env:
    global:
        - BASELINE="DynaCASEModel"
        - TESTS="DynaCASE.*"
        - PACKAGES="/repository"
        - BASELINE_GROUP="default"
