language: smalltalk
sudo: false

# Select operating system(s)
os:
  - linux
#  - osx

# Select compatible Smalltalk image(s)
smalltalk:
  - Pharo-5.0

before_install:
  - openssl aes-256-cbc -K $encrypted_e257e7f53604_key -iv $encrypted_e257e7f53604_iv -in dynacase_travis.enc -out id_dynacase_travis -d
  - chmod 0400 .ssh/id_dynacase_travis

before_script:
  - echo -e "Host ccmi.fit.cvut.cz\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
