"
Manifest for the OpenPonk Model package.
Contains metadata for reusable base classes designed to limit code duplication when building new metamodels (notations) in OpenPonk.
Usage of OpenPonk-Model is optional and might not be suitable for all kinds of models (metamodels).
"
Class {
	#name : 'ManifestOpenPonkModel',
	#superclass : 'PackageManifest',
	#category : 'OpenPonk-Model-Manifest',
	#package : 'OpenPonk-Model',
	#tag : 'Manifest'
}
